pipeline {
    agent any

    tools {
        jdk 'java11'
    }
    
    stages {
            stage('Which Java?') {
                steps {
                    sh 'java --version'
                }
            }
             stage('Compile') {
            steps {
                // Compilar la aplicación utilizando Maven
                sh 'mvn clean compile'
            }
        }
        
        stage('Package') {
            steps {
                // Empaquetar la aplicación en un archivo JAR
                sh 'mvn package'
            }
        }
    }
}
